### ISSUE TITLE
Support mounting all disks

### ISSUE THREAD

**Issue by RiRa12621** [gardener/gardener-extension-os-coreos#135]
**How to categorize this issue?**

/area enhancement
/area storage
/area os
/kind enhancement

**What would you like to be added**:
A way to mount all existing disks

**Why is this needed**:
Certain non-cloud-provider resources have pre-defined configurations for nodes, which include multiple disks. An example for this is Equinix. When spawning an instance, for example `m3.large.x86` comes with 2x 240GB SSD 2x 3.8TB NVME and as is with the spec below, gardener is only able to use the first volume, so 240g.

```
    workers:
      - cri:
          name: containerd
        kubernetes:
          version: 1.27.8
        name: worker-large
        machine:
          type: m3.large.x86
          image:
            name: flatcar
            version: 0.0.0-stable
          architecture: amd64
        maximum: 1
        minimum: 1
        maxSurge: 1
        maxUnavailable: 1
        providerConfig:
          apiVersion: equinixmetal.provider.extensions.gardener.cloud/v1alpha1
          kind: WorkerConfig
          reservationIDs:
            - SOMESPECIFICID
          reservedDevicesOnly: true
        zones:
          - fr2
        systemComponents:
          allow: true
        machineControllerManager:
          machineDrainTimeout: 2h0m0s
          machineCreationTimeout: 50m0s

```

Instead there should be a flag like `use all disks` that in turn adds a unit file to the list of unit files following https://www.flatcar.org/docs/latest/setup/storage/mounting-storage/
